### ISSUE TITLE
compilation

### ISSUE THREAD

**Issue by rodrigolealbatista** [ef15c/PS2_to_USB_converter#2]
Could you send the compiled file in Hex for recording? I have no experience with c++ only arduino ide

**Comment by ef15c** [comment]
Try https://github.com/ef15c/PS2_to_USB_converter/blob/main/stm103_ps2_to_usb/bin/Release/stm103_nrf24l01p.hex

**Comment by ef15c** [comment]
See previous comment

**Comment by rodrigolealbatista** [comment]
Friend, could you make the file available in arduino ide? I recorded it on the stm32f103c8t6 it ran normally but on the stm32f103c6t6 it didn't recognize it on the computer, with the .Ino file I can change it to the c6t6, thanks.
Yahoo Mail: Busque, organize e aumente sua produtividade 
 
  Em sex., 12 12e jul. 12e 2024 às 9:07, ***@***.***> escreveu:   


Closed #2 as completed.
