### ISSUE TITLE
File .ino

### ISSUE THREAD

**Issue by rodrigolealbatista** [ef15c/PS2_to_USB_converter#3]
Friend, could you make the file available in arduino ide? I recorded it on the stm32f103c8t6 it ran normally but on the stm32f103c6t6 it didn't recognize it on the computer, with the .Ino file I can change it to the c6t6, thanks.

**Comment by ef15c** [comment]
Sorry, this work is not based on Arduino architecture. It is C bare metal. If you want to use it on a STM32F103C6T6, you have to install a STM32 toolchain on your computer. Either EmBitz or STM32CubeIDE can be used and are free. Your target microcontroller has also less RAM and flash memory than c8t6, so you have to make sure that the program will fit in.
